### PR TITLE
[actions] Fix `get()`, `thingActions` & dynamic export of found actions

### LINKED ISSUE #164: [actions] `get()` not working
I've updated from 3.4.0M2 to latest snapshot openHAB 3.4.0 Build #3133

In UI rules I used to send a telegram message like so:
```
var telegramAction = actions.get("telegram", "telegram:telegramBot:5a3e984615");
```

This worked on 3.4.0M2, in latest snapshot I get this error:
```
2022-10-15 16:50:06.147 [ERROR] [b.automation.script.javascript.stack] - Failed to execute script:
org.graalvm.polyglot.PolyglotException: TypeError: (intermediate value).get is not a function
        at <js>.:program(<eval>:3) ~[?:?]
        at org.graalvm.polyglot.Context.eval(Context.java:379) ~[?:?]
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458) ~[?:?]
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:426) ~[?:?]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264) ~[java.scripting:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocableAndAutocloseable.eval(DelegatingScriptEngineWithInvocableAndAutocloseable.java:51) ~[?:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.eval(InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java:69) ~[?:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocableAndAutocloseable.eval(DelegatingScriptEngineWithInvocableAndAutocloseable.java:51) ~[?:?]
        at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.eval(InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java:69) ~[?:?]
        at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.lambda$0(ScriptActionHandler.java:58) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) [?:?]
        at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.execute(ScriptActionHandler.java:55) [bundleFile:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.executeActions(RuleEngineImpl.java:1181) [bundleFile:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.runRule(RuleEngineImpl.java:989) [bundleFile:?]
        at org.openhab.core.automation.internal.TriggerHandlerCallbackImpl$TriggerData.run(TriggerHandlerCallbackImpl.java:89) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

actions.get() no longer seems to be there, how can I send a telegram message?

Regards,
Bastiaan

### PR DESCRIPTION
**Pull request by florian-h05**
Fixes #164.
Caused by #148.

## Fixes
- `actions.get()` not working
- `actions.thingActions()` not working
- Dynamic exports not working
- Removed Pushsafer example from README as the Pushsafer binding does not dynamically export to the actionService.

## Test
I’ve verified that `get()`, `thingActions()` and the dynamic exports are working now.

@basvanh Can you please test this fix? 
Just run `npm install git+https://github.com/florian-h05/openhab-js.git#fix-actions-get` inside the `$OPENHAB_CONF/automation/js` folder.

### CODE REVIEW

**Review by digitaldan — APPROVED** [review]
I have not tested this, but just reading through it LGTM.

**Comment by florian-h05** [comment]
@digitaldan The creator of the issue also verified that it’s working, so I’ll merge.
